### ISSUE TITLE
Explicit type conversion in for each data row

### ISSUE THREAD

**Issue by jeancz** [contributte/application#42]
https://github.com/contributte/application/blob/f68b0a25a7eaa8a27874069d5b6cb7aeeee7888f/src/Response/CSVResponse.php#L92C31-L92C34

There should be explicit type conversion, so instead

`$csvRow = $this->printCsv($row);`

use

`$csvRow = $this->printCsv((array)$row);`

**Comment by f3l1x** [comment]
Hi. Can you please prepare PR?
